<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                     => __DIR__ . '/Module.php',
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Mongo\AuthDbFactory'        => __DIR__ . '/src/Application/Mongo/AuthDbFactory.php',
  'Application\Mongo\MongoClientFactory'   => __DIR__ . '/src/Application/Mongo/MongoClientFactory.php',
);
