<?php
/**
 * Magic Card Keeper
 *
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 *
 * @link      https://github.com/manchuck/magic-card-keeper for the canonical source repository
 * @copyright Copyright (c) 2014 Chuck "MANCHUCK" Reeves (http://www.manchuck.com)
 * @license   See LICENSE.txt
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
?>
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
<?php
    echo $this->headTitle('Apigility');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.ico')])
        ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
        ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));
    echo $this->headScript()
        ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
        ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>

    </head>
    <body>
        <header class="navbar navbar-inverse navbar-fixed-top primary" role="navigation">
            <a class="sr-only" href="#content"> … </a>
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="<?php echo $this->url('home') ?>" class="navbar-brand">
                        <img src="<?php echo $this->basePath('/zf-apigility/img/ag-logo.png') ?>">
                    </a>
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".ag-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse ag-navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if (class_exists('ZF\Apigility\Admin\Module', false)): ?>
                            <li><a href="<?php echo $this->url('zf-apigility/ui') ?>">Admin</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </header>

        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

        <footer>
            <hr>
            <div class="container center-block">
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
