<?php
/**
 * Magic Card Keeper
 *
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 *
 * @link      https://github.com/manchuck/magic-card-keeper for the canonical source repository
 * @copyright Copyright (c) 2014 Chuck "MANCHUCK" Reeves (http://www.manchuck.com)
 * @license   See LICENSE.txt
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
?>
<div class="hero-unit">
    <h1>ZF API First Application</h1>
    <p>Hero image here</p>
</div>

<div class="row">
    <div class="span12">
        <h2>Getting Started</h2>
        <p>It it important that your application be put into development mode in order to start using the ZF API First Administration screens to assist building your app.</p>
        <p>Currently, your application <b><?php echo (class_exists('ZF\ApiFirstAdmin\Module', false)) ? 'IS' : 'IS NOT' ?></b> in development mode.  Here are some instructions on how to do it:</p>
    </div>
</div>
